build_root:
  project_image:
    dockerfile_path: scripts/Dockerfile.test
images:
- dockerfile_path: redhat/Containerfile
  to: ceph-csi
resources:
  '*':
    requests:
      cpu: 100m
      memory: 1Gi
tests:
- as: static-checks
  commands: |
    set -x
    rm -rf ../../ceph/ceph-csi ; ln -s ../red-hat-storage/ceph-csi ../../ceph/ceph-csi
    cd ../../ceph/ceph-csi
    GOMODCACHE=/tmp/mod-cache GOCACHE=/tmp XDG_CACHE_HOME=/tmp PYLINTHOME=/tmp make cephcsi test
  container:
    from: src
zz_generated_metadata:
  branch: release-4.9
  org: red-hat-storage
  repo: ceph-csi
